### PR TITLE
Trim suffix from wine version

### LINKED ISSUE #1031: TypeError: Invalid Version: 2.0-rc1.0
* **Version**: 10.9.2

* **Target**: -w --x64 --ia32

I try build Windows App on Linux (Ubuntu 16.10);
In my dev package.json:
```json
{
  "name": "ad_maker",
  "version": "1.1.0",
  ...
  "build": {
    "linux": {
      "target": "snap",
      "category": "Utility"
    },
    "win": {
      "target": "zip"
    }
  },
  "directories": {}
}
```

In my APP package.json:
```json
{
  "name": "ad_maker",
  "version": "1.1.0",
  ...
  "main": "main.js",
}
```

As you can see both versions of a file is written as **1.1.0**. But console command 
```bash
build -w --x64 --ia32
```
returns an error:
```bash
TypeError: Invalid Version: 2.0-rc1.0
    at new SemVer (/home/alex/Develop/electron-build/node_modules/semver/semver.js:293:11)
    at compare (/home/alex/Develop/electron-build/node_modules/semver/semver.js:566:10)
    at lt (/home/alex/Develop/electron-build/node_modules/semver/semver.js:600:10)
    at /home/alex/Develop/electron-build/node_modules/electron-builder/src/packager.ts:327:7
From previous event:
    at checkWineVersion (/home/alex/Develop/electron-build/node_modules/electron-builder/out/packager.js:53:22)
    at /home/alex/Develop/electron-build/node_modules/electron-builder/src/packager.ts:143:17
From previous event:
    at Packager.doBuild (/home/alex/Develop/electron-build/node_modules/electron-builder/out/packager.js:271:11
)
    at /home/alex/Develop/electron-build/node_modules/electron-builder/src/packager.ts:114:38
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/home/alex/Develop/electron-build/node_modules/electron-builder/out/packager.js:223:11)
    at /home/alex/Develop/electron-build/node_modules/electron-builder/src/builder.ts:241:40
    at next (native)
From previous event:
    at build (/home/alex/Develop/electron-build/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/home/alex/Develop/electron-build/node_modules/electron-builder/out/cli/build-cli.js
:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
In the dependencies I have not found any such package version.

[npm-debug.txt](https://github.com/electron-userland/electron-builder/files/663479/npm-debug.txt)

### PR DESCRIPTION
**Pull request by cawa-93**
This is fix #1031 and #953  issue

### CODE REVIEW

File: src/packager.ts [hunk 1]
```diff
@@ -320,6 +320,11 @@ export async function checkWineVersion(checkPromise: Promise<string>) {
     wineVersion = wineVersion.substring(0, spaceIndex)
   }
 
+  const rcIndex = wineVersion.indexOf("-rc")
```
Comment (cawa-93) [inline src/packager.ts]: Then it may be simply makes sense to replace all "-" on "."? In this case, you will see the difference between wine-2.0-rc1 and wine-2.0-rc2. They will be given to the form and 2.0.rc1 2.0.rc1. Semver be able to recognize this type of version?

**Comment by develar** [comment]
Thanks for PR!
