### PR TITLE
fix(mac): normalize filename to NFD form

### LINKED ISSUE #6912: Helper (GPU).app/Contents/MacOS/myapp Helper (GPU).app: code object is not signed at all
* **Electron-Builder Version**: 
v23.0.3

* **Node Version**: 
v16.15.0

* **Electron Version**: v18.2.3
* **Electron Type (current, beta, nightly)**:

Current

* **Target**: macOS

So basically, when I try to sign with a valid Apple Dev Id, I get this error.
Here is workflow run: https://github.com/ZeotYT/PokeLauncher-v2/runs/6684752383
Can you help me?
Thanks in advance for your answers

### PR DESCRIPTION
**Pull request by jebibot**
Fixes issues when `productName` and `executableName` contain characters that have different NFC and NFD form, e.g., diacritics and Hangul (Korean). These seem to be internally normalized to the NFD form at some point, failing string comparison and other operations. Specifically,
- fixes codesign failing with `code object is not signed at all In subcomponent:`,
  - fixes #6912
  - https://github.com/electron-userland/electron-builder/issues/3169#issuecomment-800113654
  - #5977
  - https://github.com/electron/osx-sign/issues/155
- fixes DMG layout,
  - #1234
  - #1369
  - #6282
- and possibly related:
  - #2125
  - #4697

### CODE REVIEW

File: packages/app-builder-lib/src/util/filename.ts [hunk 1]
```diff
@@ -2,8 +2,9 @@
 import * as _sanitizeFileName from "sanitize-filename"
 import * as path from "path"
 
-export function sanitizeFileName(s: string): string {
-  return _sanitizeFileName(s)
+export function sanitizeFileName(s: string, normalizeNfd = false): string {
+  const sanitized = _sanitizeFileName(s)
+  return normalizeNfd ? sanitized.normalize("NFD") : sanitized
```
Comment (mmaietta) [inline packages/app-builder-lib/src/util/filename.ts:7]: What is `normalize("NFD")`? I don't see it in the API or type definitions: https://github.com/parshap/node-sanitize-filename/blob/master/index.d.ts

Comment (mmaietta) [reply packages/app-builder-lib/src/util/filename.ts:7]: Thank you for clarifying, and I appreciate the links as well!
